2025-04-06 22:31:01,891 - INFO - 🔹 Reading processed dataset...
2025-04-06 22:31:01,912 - INFO - 🔹 Generating statistics from dataset...
2025-04-06 22:31:02,122 - INFO - 📥 No existing schema. Inferring and saving new schema...
2025-04-06 22:31:02,126 - INFO - ✅ New schema saved to: /home/runner/work/MLOPS-Sentiment-Analyzer-Project/MLOPS-Sentiment-Analyzer-Project/Data_Pipeline/validation/schema.pbtxt
2025-04-06 22:31:02,128 - INFO - ✅ Reference stats saved to: /home/runner/work/MLOPS-Sentiment-Analyzer-Project/MLOPS-Sentiment-Analyzer-Project/Data_Pipeline/validation/reference_stats.tfrecord
2025-04-06 22:44:48,158 - INFO - 🔹 Reading processed dataset...
2025-04-06 22:44:48,178 - INFO - 🔹 Generating statistics from dataset...
2025-04-06 22:44:48,384 - INFO - 🔍 Schema exists. Validating against it...
2025-04-06 22:44:48,388 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-06 22:54:54,984 - INFO - 🔹 Reading processed dataset...
2025-04-06 22:54:55,004 - INFO - 🔹 Generating statistics from dataset...
2025-04-06 22:54:55,213 - INFO - 🔍 Schema exists. Validating against it...
2025-04-06 22:54:55,218 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-06 23:25:23,658 - INFO - 🔹 Reading processed dataset...
2025-04-06 23:25:23,678 - INFO - 🔹 Generating statistics from dataset...
2025-04-06 23:25:23,892 - INFO - 🔍 Schema exists. Validating against it...
2025-04-06 23:25:23,897 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-07 00:08:04,163 - INFO - 🔹 Reading processed dataset...
2025-04-07 00:08:09,623 - INFO - 🔹 Generating statistics from dataset...
2025-04-07 00:08:25,999 - INFO - 🔍 Schema exists. Validating against it...
2025-04-07 00:08:26,004 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-07 00:34:44,110 - INFO - 🔹 Reading processed dataset...
2025-04-07 00:34:44,130 - INFO - 🔹 Generating statistics from dataset...
2025-04-07 00:34:44,209 - INFO - 🔍 Schema exists. Validating against it...
2025-04-07 00:34:44,214 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-07 01:03:29,858 - INFO - 🔹 Reading processed dataset...
2025-04-07 01:03:29,879 - INFO - 🔹 Generating statistics from dataset...
2025-04-07 01:03:29,959 - INFO - 🔍 Schema exists. Validating against it...
2025-04-07 01:03:29,963 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-07 04:19:51,483 - INFO - 🔹 Reading processed dataset...
2025-04-07 04:19:51,504 - INFO - 🔹 Generating statistics from dataset...
2025-04-07 04:19:51,584 - INFO - 🔍 Schema exists. Validating against it...
2025-04-07 04:19:51,588 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-08 01:34:36,452 - INFO - 🔹 Reading processed dataset...
2025-04-08 01:34:36,472 - INFO - 🔹 Generating statistics from dataset...
2025-04-08 01:34:36,552 - INFO - 🔍 Schema exists. Validating against it...
2025-04-08 01:34:36,556 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 04:08:39,115 - INFO - 🔹 Reading processed dataset...
2025-04-11 04:08:39,136 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 04:08:39,215 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 04:08:39,220 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 04:13:33,383 - INFO - 🔹 Reading processed dataset...
2025-04-11 04:13:33,405 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 04:13:33,484 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 04:13:33,488 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 04:31:18,140 - INFO - 🔹 Reading processed dataset...
2025-04-11 04:31:18,160 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 04:31:18,238 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 04:31:18,243 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 04:40:30,557 - INFO - 🔹 Reading processed dataset...
2025-04-11 04:40:30,578 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 04:40:30,658 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 04:40:30,663 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 05:03:58,927 - INFO - 🔹 Reading processed dataset...
2025-04-11 05:03:58,946 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 05:03:59,025 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 05:03:59,030 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 05:08:55,257 - INFO - 🔹 Reading processed dataset...
2025-04-11 05:08:55,279 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 05:08:55,360 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 05:08:55,365 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 06:33:05,784 - INFO - 🔹 Reading processed dataset...
2025-04-11 06:33:05,804 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 06:33:05,919 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 06:33:05,923 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 06:50:05,780 - INFO - 🔹 Reading processed dataset...
2025-04-11 06:50:05,800 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 06:50:05,878 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 06:50:05,883 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 12:59:02,369 - INFO - 🔹 Reading processed dataset...
2025-04-11 12:59:02,389 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 12:59:02,470 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 12:59:02,474 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 13:03:24,130 - INFO - 🔹 Reading processed dataset...
2025-04-11 13:03:24,152 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 13:03:24,230 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 13:03:24,235 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 13:07:43,690 - INFO - 🔹 Reading processed dataset...
2025-04-11 13:07:43,710 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 13:07:43,789 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 13:07:43,794 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 13:26:27,595 - INFO - 🔹 Reading processed dataset...
2025-04-11 13:26:27,616 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 13:26:27,695 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 13:26:27,700 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 13:30:11,455 - INFO - 🔹 Reading processed dataset...
2025-04-11 13:30:11,476 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 13:30:11,557 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 13:30:11,562 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 13:34:03,330 - INFO - 🔹 Reading processed dataset...
2025-04-11 13:34:03,351 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 13:34:03,431 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 13:34:03,435 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 13:37:47,987 - INFO - 🔹 Reading processed dataset...
2025-04-11 13:37:48,008 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 13:37:48,097 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 13:37:48,101 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
