2025-04-06 22:31:01,891 - INFO - 🔹 Reading processed dataset...
2025-04-06 22:31:01,912 - INFO - 🔹 Generating statistics from dataset...
2025-04-06 22:31:02,122 - INFO - 📥 No existing schema. Inferring and saving new schema...
2025-04-06 22:31:02,126 - INFO - ✅ New schema saved to: /home/runner/work/MLOPS-Sentiment-Analyzer-Project/MLOPS-Sentiment-Analyzer-Project/Data_Pipeline/validation/schema.pbtxt
2025-04-06 22:31:02,128 - INFO - ✅ Reference stats saved to: /home/runner/work/MLOPS-Sentiment-Analyzer-Project/MLOPS-Sentiment-Analyzer-Project/Data_Pipeline/validation/reference_stats.tfrecord
2025-04-06 22:44:48,158 - INFO - 🔹 Reading processed dataset...
2025-04-06 22:44:48,178 - INFO - 🔹 Generating statistics from dataset...
2025-04-06 22:44:48,384 - INFO - 🔍 Schema exists. Validating against it...
2025-04-06 22:44:48,388 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-06 22:54:54,984 - INFO - 🔹 Reading processed dataset...
2025-04-06 22:54:55,004 - INFO - 🔹 Generating statistics from dataset...
2025-04-06 22:54:55,213 - INFO - 🔍 Schema exists. Validating against it...
2025-04-06 22:54:55,218 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-06 23:25:23,658 - INFO - 🔹 Reading processed dataset...
2025-04-06 23:25:23,678 - INFO - 🔹 Generating statistics from dataset...
2025-04-06 23:25:23,892 - INFO - 🔍 Schema exists. Validating against it...
2025-04-06 23:25:23,897 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-07 00:08:04,163 - INFO - 🔹 Reading processed dataset...
2025-04-07 00:08:09,623 - INFO - 🔹 Generating statistics from dataset...
2025-04-07 00:08:25,999 - INFO - 🔍 Schema exists. Validating against it...
2025-04-07 00:08:26,004 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-07 00:34:44,110 - INFO - 🔹 Reading processed dataset...
2025-04-07 00:34:44,130 - INFO - 🔹 Generating statistics from dataset...
2025-04-07 00:34:44,209 - INFO - 🔍 Schema exists. Validating against it...
2025-04-07 00:34:44,214 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-07 01:03:29,858 - INFO - 🔹 Reading processed dataset...
2025-04-07 01:03:29,879 - INFO - 🔹 Generating statistics from dataset...
2025-04-07 01:03:29,959 - INFO - 🔍 Schema exists. Validating against it...
2025-04-07 01:03:29,963 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-07 04:19:51,483 - INFO - 🔹 Reading processed dataset...
2025-04-07 04:19:51,504 - INFO - 🔹 Generating statistics from dataset...
2025-04-07 04:19:51,584 - INFO - 🔍 Schema exists. Validating against it...
2025-04-07 04:19:51,588 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-08 01:34:36,452 - INFO - 🔹 Reading processed dataset...
2025-04-08 01:34:36,472 - INFO - 🔹 Generating statistics from dataset...
2025-04-08 01:34:36,552 - INFO - 🔍 Schema exists. Validating against it...
2025-04-08 01:34:36,556 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 04:08:39,115 - INFO - 🔹 Reading processed dataset...
2025-04-11 04:08:39,136 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 04:08:39,215 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 04:08:39,220 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 04:13:33,383 - INFO - 🔹 Reading processed dataset...
2025-04-11 04:13:33,405 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 04:13:33,484 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 04:13:33,488 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 04:31:18,140 - INFO - 🔹 Reading processed dataset...
2025-04-11 04:31:18,160 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 04:31:18,238 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 04:31:18,243 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 04:40:30,557 - INFO - 🔹 Reading processed dataset...
2025-04-11 04:40:30,578 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 04:40:30,658 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 04:40:30,663 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 05:03:58,927 - INFO - 🔹 Reading processed dataset...
2025-04-11 05:03:58,946 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 05:03:59,025 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 05:03:59,030 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 05:08:55,257 - INFO - 🔹 Reading processed dataset...
2025-04-11 05:08:55,279 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 05:08:55,360 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 05:08:55,365 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 06:33:05,784 - INFO - 🔹 Reading processed dataset...
2025-04-11 06:33:05,804 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 06:33:05,919 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 06:33:05,923 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 06:50:05,780 - INFO - 🔹 Reading processed dataset...
2025-04-11 06:50:05,800 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 06:50:05,878 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 06:50:05,883 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 12:59:02,369 - INFO - 🔹 Reading processed dataset...
2025-04-11 12:59:02,389 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 12:59:02,470 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 12:59:02,474 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 13:03:24,130 - INFO - 🔹 Reading processed dataset...
2025-04-11 13:03:24,152 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 13:03:24,230 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 13:03:24,235 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 13:07:43,690 - INFO - 🔹 Reading processed dataset...
2025-04-11 13:07:43,710 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 13:07:43,789 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 13:07:43,794 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 13:26:27,595 - INFO - 🔹 Reading processed dataset...
2025-04-11 13:26:27,616 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 13:26:27,695 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 13:26:27,700 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 13:30:11,455 - INFO - 🔹 Reading processed dataset...
2025-04-11 13:30:11,476 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 13:30:11,557 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 13:30:11,562 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 13:34:03,330 - INFO - 🔹 Reading processed dataset...
2025-04-11 13:34:03,351 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 13:34:03,431 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 13:34:03,435 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 13:37:47,987 - INFO - 🔹 Reading processed dataset...
2025-04-11 13:37:48,008 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 13:37:48,097 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 13:37:48,101 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 13:41:29,429 - INFO - 🔹 Reading processed dataset...
2025-04-11 13:41:29,449 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 13:41:29,528 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 13:41:29,533 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 13:45:27,609 - INFO - 🔹 Reading processed dataset...
2025-04-11 13:45:27,630 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 13:45:27,711 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 13:45:27,715 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 13:49:09,480 - INFO - 🔹 Reading processed dataset...
2025-04-11 13:49:09,501 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 13:49:09,580 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 13:49:09,585 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 13:52:51,497 - INFO - 🔹 Reading processed dataset...
2025-04-11 13:52:51,518 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 13:52:51,598 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 13:52:51,602 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 13:56:38,458 - INFO - 🔹 Reading processed dataset...
2025-04-11 13:56:38,479 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 13:56:38,558 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 13:56:38,562 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 14:00:15,509 - INFO - 🔹 Reading processed dataset...
2025-04-11 14:00:15,529 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 14:00:15,608 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 14:00:15,612 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 14:04:00,071 - INFO - 🔹 Reading processed dataset...
2025-04-11 14:04:00,093 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 14:04:00,176 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 14:04:00,180 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 14:07:48,946 - INFO - 🔹 Reading processed dataset...
2025-04-11 14:07:48,966 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 14:07:49,046 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 14:07:49,051 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 14:11:27,629 - INFO - 🔹 Reading processed dataset...
2025-04-11 14:11:27,649 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 14:11:27,729 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 14:11:27,733 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 14:15:15,771 - INFO - 🔹 Reading processed dataset...
2025-04-11 14:15:15,791 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 14:15:15,870 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 14:15:15,875 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 14:19:09,913 - INFO - 🔹 Reading processed dataset...
2025-04-11 14:19:09,935 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 14:19:10,015 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 14:19:10,020 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 14:23:02,786 - INFO - 🔹 Reading processed dataset...
2025-04-11 14:23:02,807 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 14:23:02,888 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 14:23:02,893 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 14:26:50,571 - INFO - 🔹 Reading processed dataset...
2025-04-11 14:26:50,591 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 14:26:50,672 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 14:26:50,677 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 14:30:47,528 - INFO - 🔹 Reading processed dataset...
2025-04-11 14:30:47,548 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 14:30:47,626 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 14:30:47,631 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 14:34:31,761 - INFO - 🔹 Reading processed dataset...
2025-04-11 14:34:31,782 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 14:34:31,861 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 14:34:31,865 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 14:38:07,042 - INFO - 🔹 Reading processed dataset...
2025-04-11 14:38:07,063 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 14:38:07,142 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 14:38:07,146 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 14:41:59,580 - INFO - 🔹 Reading processed dataset...
2025-04-11 14:41:59,601 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 14:41:59,684 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 14:41:59,688 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 14:45:44,543 - INFO - 🔹 Reading processed dataset...
2025-04-11 14:45:44,563 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 14:45:44,642 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 14:45:44,646 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 14:49:42,298 - INFO - 🔹 Reading processed dataset...
2025-04-11 14:49:42,320 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 14:49:42,400 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 14:49:42,404 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 14:53:37,595 - INFO - 🔹 Reading processed dataset...
2025-04-11 14:53:37,619 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 14:53:37,701 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 14:53:37,705 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 14:57:21,752 - INFO - 🔹 Reading processed dataset...
2025-04-11 14:57:21,773 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 14:57:21,853 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 14:57:21,857 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 15:01:05,289 - INFO - 🔹 Reading processed dataset...
2025-04-11 15:01:05,309 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 15:01:05,389 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 15:01:05,393 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 15:04:46,441 - INFO - 🔹 Reading processed dataset...
2025-04-11 15:04:46,462 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 15:04:46,544 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 15:04:46,549 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 15:08:30,480 - INFO - 🔹 Reading processed dataset...
2025-04-11 15:08:30,500 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 15:08:30,580 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 15:08:30,584 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 15:12:20,566 - INFO - 🔹 Reading processed dataset...
2025-04-11 15:12:20,587 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 15:12:20,709 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 15:12:20,716 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 15:16:21,484 - INFO - 🔹 Reading processed dataset...
2025-04-11 15:16:21,505 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 15:16:21,586 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 15:16:21,591 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 21:00:05,106 - INFO - 🔹 Reading processed dataset...
2025-04-11 21:00:05,126 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 21:00:05,207 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 21:00:05,212 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 21:04:00,065 - INFO - 🔹 Reading processed dataset...
2025-04-11 21:04:00,090 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 21:04:00,169 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 21:04:00,173 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 21:07:33,573 - INFO - 🔹 Reading processed dataset...
2025-04-11 21:07:33,594 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 21:07:33,673 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 21:07:33,677 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 21:11:23,716 - INFO - 🔹 Reading processed dataset...
2025-04-11 21:11:23,736 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 21:11:23,815 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 21:11:23,819 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 21:15:13,697 - INFO - 🔹 Reading processed dataset...
2025-04-11 21:15:13,718 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 21:15:13,798 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 21:15:13,802 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 21:18:57,471 - INFO - 🔹 Reading processed dataset...
2025-04-11 21:18:57,492 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 21:18:57,572 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 21:18:57,576 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 21:22:42,866 - INFO - 🔹 Reading processed dataset...
2025-04-11 21:22:42,886 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 21:22:42,966 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 21:22:42,971 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 21:26:20,321 - INFO - 🔹 Reading processed dataset...
2025-04-11 21:26:20,341 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 21:26:20,420 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 21:26:20,424 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 21:30:22,861 - INFO - 🔹 Reading processed dataset...
2025-04-11 21:30:22,882 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 21:30:22,963 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 21:30:22,968 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 21:34:11,623 - INFO - 🔹 Reading processed dataset...
2025-04-11 21:34:11,645 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 21:34:11,726 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 21:34:11,730 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 21:38:05,362 - INFO - 🔹 Reading processed dataset...
2025-04-11 21:38:05,383 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 21:38:05,464 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 21:38:05,469 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 21:41:56,839 - INFO - 🔹 Reading processed dataset...
2025-04-11 21:41:56,860 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 21:41:56,938 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 21:41:56,942 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 21:45:48,974 - INFO - 🔹 Reading processed dataset...
2025-04-11 21:45:48,995 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 21:45:49,076 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 21:45:49,080 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 21:49:31,005 - INFO - 🔹 Reading processed dataset...
2025-04-11 21:49:31,026 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 21:49:31,106 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 21:49:31,111 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 21:53:12,746 - INFO - 🔹 Reading processed dataset...
2025-04-11 21:53:12,767 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 21:53:12,846 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 21:53:12,851 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 21:56:51,392 - INFO - 🔹 Reading processed dataset...
2025-04-11 21:56:51,412 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 21:56:51,491 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 21:56:51,496 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 22:00:31,386 - INFO - 🔹 Reading processed dataset...
2025-04-11 22:00:31,406 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 22:00:31,485 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 22:00:31,490 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 22:04:25,201 - INFO - 🔹 Reading processed dataset...
2025-04-11 22:04:25,222 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 22:04:25,303 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 22:04:25,308 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 22:08:12,879 - INFO - 🔹 Reading processed dataset...
2025-04-11 22:08:12,900 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 22:08:12,979 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 22:08:12,983 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 22:11:47,473 - INFO - 🔹 Reading processed dataset...
2025-04-11 22:11:47,494 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 22:11:47,574 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 22:11:47,579 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 22:15:31,561 - INFO - 🔹 Reading processed dataset...
2025-04-11 22:15:31,582 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 22:15:31,660 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 22:15:31,665 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 22:19:10,824 - INFO - 🔹 Reading processed dataset...
2025-04-11 22:19:10,844 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 22:19:10,923 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 22:19:10,928 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 22:22:44,415 - INFO - 🔹 Reading processed dataset...
2025-04-11 22:22:44,435 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 22:22:44,514 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 22:22:44,519 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 22:26:21,735 - INFO - 🔹 Reading processed dataset...
2025-04-11 22:26:21,756 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 22:26:21,836 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 22:26:21,840 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 22:30:07,821 - INFO - 🔹 Reading processed dataset...
2025-04-11 22:30:07,842 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 22:30:07,922 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 22:30:07,927 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 22:33:47,371 - INFO - 🔹 Reading processed dataset...
2025-04-11 22:33:47,392 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 22:33:47,473 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 22:33:47,477 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 22:37:22,472 - INFO - 🔹 Reading processed dataset...
2025-04-11 22:37:22,493 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 22:37:22,572 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 22:37:22,577 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 22:41:00,474 - INFO - 🔹 Reading processed dataset...
2025-04-11 22:41:00,496 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 22:41:00,588 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 22:41:00,593 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 22:44:37,274 - INFO - 🔹 Reading processed dataset...
2025-04-11 22:44:37,296 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 22:44:37,375 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 22:44:37,379 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 22:48:17,099 - INFO - 🔹 Reading processed dataset...
2025-04-11 22:48:17,119 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 22:48:17,198 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 22:48:17,202 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 22:51:58,298 - INFO - 🔹 Reading processed dataset...
2025-04-11 22:51:58,318 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 22:51:58,397 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 22:51:58,402 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 22:55:38,338 - INFO - 🔹 Reading processed dataset...
2025-04-11 22:55:38,358 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 22:55:38,437 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 22:55:38,441 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 22:59:18,364 - INFO - 🔹 Reading processed dataset...
2025-04-11 22:59:18,385 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 22:59:18,464 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 22:59:18,468 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 23:03:06,062 - INFO - 🔹 Reading processed dataset...
2025-04-11 23:03:06,083 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 23:03:06,162 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 23:03:06,166 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 23:06:57,645 - INFO - 🔹 Reading processed dataset...
2025-04-11 23:06:57,666 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 23:06:57,768 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 23:06:57,773 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 23:10:33,436 - INFO - 🔹 Reading processed dataset...
2025-04-11 23:10:33,456 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 23:10:33,535 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 23:10:33,539 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 23:14:07,081 - INFO - 🔹 Reading processed dataset...
2025-04-11 23:14:07,101 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 23:14:07,181 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 23:14:07,186 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 23:17:47,591 - INFO - 🔹 Reading processed dataset...
2025-04-11 23:17:47,612 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 23:17:47,691 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 23:17:47,696 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 23:21:24,813 - INFO - 🔹 Reading processed dataset...
2025-04-11 23:21:24,833 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 23:21:24,912 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 23:21:24,916 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 23:25:15,413 - INFO - 🔹 Reading processed dataset...
2025-04-11 23:25:15,434 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 23:25:15,514 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 23:25:15,519 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 23:29:06,335 - INFO - 🔹 Reading processed dataset...
2025-04-11 23:29:06,355 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 23:29:06,434 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 23:29:06,438 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 23:32:43,732 - INFO - 🔹 Reading processed dataset...
2025-04-11 23:32:43,753 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 23:32:43,832 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 23:32:43,837 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 23:36:37,552 - INFO - 🔹 Reading processed dataset...
2025-04-11 23:36:37,572 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 23:36:37,650 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 23:36:37,655 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 23:40:28,746 - INFO - 🔹 Reading processed dataset...
2025-04-11 23:40:28,767 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 23:40:28,847 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 23:40:28,852 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 23:44:10,022 - INFO - 🔹 Reading processed dataset...
2025-04-11 23:44:10,043 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 23:44:10,122 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 23:44:10,126 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 23:47:55,019 - INFO - 🔹 Reading processed dataset...
2025-04-11 23:47:55,040 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 23:47:55,124 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 23:47:55,128 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 23:51:34,401 - INFO - 🔹 Reading processed dataset...
2025-04-11 23:51:34,421 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 23:51:34,500 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 23:51:34,504 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 23:55:11,423 - INFO - 🔹 Reading processed dataset...
2025-04-11 23:55:11,445 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 23:55:11,525 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 23:55:11,529 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 23:58:40,449 - INFO - 🔹 Reading processed dataset...
2025-04-11 23:58:40,469 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 23:58:40,549 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 23:58:40,553 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-12 00:02:13,441 - INFO - 🔹 Reading processed dataset...
2025-04-12 00:02:13,461 - INFO - 🔹 Generating statistics from dataset...
2025-04-12 00:02:13,540 - INFO - 🔍 Schema exists. Validating against it...
2025-04-12 00:02:13,544 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-12 00:05:50,451 - INFO - 🔹 Reading processed dataset...
2025-04-12 00:05:50,472 - INFO - 🔹 Generating statistics from dataset...
2025-04-12 00:05:50,551 - INFO - 🔍 Schema exists. Validating against it...
2025-04-12 00:05:50,555 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-12 00:09:28,567 - INFO - 🔹 Reading processed dataset...
2025-04-12 00:09:28,587 - INFO - 🔹 Generating statistics from dataset...
2025-04-12 00:09:28,667 - INFO - 🔍 Schema exists. Validating against it...
2025-04-12 00:09:28,671 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-12 00:13:01,698 - INFO - 🔹 Reading processed dataset...
2025-04-12 00:13:01,718 - INFO - 🔹 Generating statistics from dataset...
2025-04-12 00:13:01,801 - INFO - 🔍 Schema exists. Validating against it...
2025-04-12 00:13:01,805 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-12 00:16:52,741 - INFO - 🔹 Reading processed dataset...
2025-04-12 00:16:52,762 - INFO - 🔹 Generating statistics from dataset...
2025-04-12 00:16:52,841 - INFO - 🔍 Schema exists. Validating against it...
2025-04-12 00:16:52,845 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-12 00:20:23,392 - INFO - 🔹 Reading processed dataset...
2025-04-12 00:20:23,414 - INFO - 🔹 Generating statistics from dataset...
2025-04-12 00:20:23,493 - INFO - 🔍 Schema exists. Validating against it...
2025-04-12 00:20:23,498 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-12 00:24:03,104 - INFO - 🔹 Reading processed dataset...
2025-04-12 00:24:03,124 - INFO - 🔹 Generating statistics from dataset...
2025-04-12 00:24:03,205 - INFO - 🔍 Schema exists. Validating against it...
2025-04-12 00:24:03,209 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-12 00:27:43,591 - INFO - 🔹 Reading processed dataset...
2025-04-12 00:27:43,611 - INFO - 🔹 Generating statistics from dataset...
2025-04-12 00:27:43,690 - INFO - 🔍 Schema exists. Validating against it...
2025-04-12 00:27:43,694 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-12 00:31:13,133 - INFO - 🔹 Reading processed dataset...
2025-04-12 00:31:13,153 - INFO - 🔹 Generating statistics from dataset...
2025-04-12 00:31:13,232 - INFO - 🔍 Schema exists. Validating against it...
2025-04-12 00:31:13,237 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-12 00:35:14,589 - INFO - 🔹 Reading processed dataset...
2025-04-12 00:35:14,609 - INFO - 🔹 Generating statistics from dataset...
2025-04-12 00:35:14,687 - INFO - 🔍 Schema exists. Validating against it...
2025-04-12 00:35:14,691 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-12 00:38:52,643 - INFO - 🔹 Reading processed dataset...
2025-04-12 00:38:52,664 - INFO - 🔹 Generating statistics from dataset...
2025-04-12 00:38:52,743 - INFO - 🔍 Schema exists. Validating against it...
2025-04-12 00:38:52,747 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-12 00:42:49,984 - INFO - 🔹 Reading processed dataset...
2025-04-12 00:42:50,004 - INFO - 🔹 Generating statistics from dataset...
2025-04-12 00:42:50,083 - INFO - 🔍 Schema exists. Validating against it...
2025-04-12 00:42:50,087 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-12 00:46:34,624 - INFO - 🔹 Reading processed dataset...
2025-04-12 00:46:34,645 - INFO - 🔹 Generating statistics from dataset...
2025-04-12 00:46:34,724 - INFO - 🔍 Schema exists. Validating against it...
2025-04-12 00:46:34,728 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
